### ISSUE TITLE
Include type signature in "Positional element is not found" error

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#101]
If there are any positional arguments missing when calling a function the compiler complains with:
```
******************** Type error
Positional element is not found
```
the error message should include:
- source code line where the function / method is being called
- type signature of the called function / method

**Comment by nordlander** [comment]
@plajjan I agree that this is perhaps the most annoying aspect of the virtually non-existing type error messages of actonc. But the solution would still be just an instance of the general error reporting mechanism I'm eager to implement!

**Comment by plajjan** [comment]
Ok, yeah, I'm naturally fine with this being implemented as the all-generic-error-reporting-mechanism, just noting it down as it's really quite non-descript in its current form. Other messages are cryptic, like using internal variable names, but at least just having some identifiers makes it possible for me to notice things changing when I change the source. With this completely generic message, I can't tell at all where in the program the error is.

**Comment by plajjan** [comment]
I created a GitHub project where I've added this and a bunch of other issues. Unlike the standard issue list here on GitHub, a project allows ordering the issues in a particular order. I have done that in what I think is the current prio order. Feel free to check it out - https://github.com/actonlang/acton/projects/5 and see if you agree on priority or note. I don't feel super strongly about the current prio, but it would be good to establish an order I think.

There are also different columns for to do, if it is in progress or if it is complete. I think you are currently working on #100 (sort of indirectly, you would probably call it something grander) and so I marked it as in progress.

**Comment by plajjan** [comment]
@nordlander so I've been bit by this a few more times and what I don't get is why there is no location to a positional error. I mean, general error handling bla bla is great but why not just add a position to PosElemNotFound first?

```haskell
instance HasLoc TypeError where
    loc (TypeError l str)           = l
    loc (RigidVariable tv)          = loc tv
    loc (InfiniteType tv)           = loc tv
    loc (ConflictingRow tv)         = loc tv
    loc (KwdNotFound n)             = loc n
    loc (PosElemNotFound)           = NoLoc     -- TODO: supply position
    loc (EscapingVar tvs t)         = loc tvs
    loc (NoSelStatic n u)           = loc n
    loc (NoSelInstByClass n u)      = loc n
    loc (NoMut n)                   = loc n
    loc (LackSig n)                 = loc n
    loc (LackDef n)                 = loc n
    loc (NoRed c)                   = loc c
    loc (NoSolve cs)                = loc cs
    loc (NoUnify t1 t2)             = loc t1
```

PosElemNotFound is the only one lacking a position. Is there a particular reason for this?

**Comment by plajjan** [comment]
The reason the position is missing is that we don't know a positional argument is missing until quite "late" in the compiler, we need to run through a couple of passes and at that point we've lost the location information. We need to bring it along further and that's why this ticket isn't quite the "just-fix-it" which I have so far assumed.

**Comment by plajjan** [comment]
I think we can close this now as the base problem of including a source code location is solved. There are however cases where the position is not correctly reported, in particular after #1609 it seems we have some regressions, e.g. #1610. It's better to open more specific and actionable issues though, which is why I'll close this in preference of #1610 and potentially others.
