### ISSUE TITLE
Arithmetic operations produce wrong result or loop indefinitely with hexadecimal literals

### ISSUE THREAD

**Issue by ddjoh** [actonlang/acton#1027]
### Acton Version

0.12.0.20221031.13.5.42

### Steps to Reproduce

Compile and run:
```
actor main(env):
    print("Try hex...")
    print("Test0:", 10 + 0x3)
    print("Test1:", 10 - 0x3)
    print("Test2:", 10 * 0x3)
    print("Test3:", 10 // 0x3)
    print("Test4:", 10 % 0x3)
    await async env.exit(0)
```

### Expected Behavior

Output:
```
Try hex...
Test0: 13
Test1: 7
Test2: 30
Test3: 3
Test4: 1
```

### Actual Behavior

Output:
```
Try hex...
Test0: 10
Test1: 10
Test2: 0
```

**Comment by plajjan** [comment]
I can reproduce on my machine and the generated C code doesn't look awfully weird so I give it a 51% / 49% of being in the builtins ;)

@sydow your the "builtins guy", wanna have a look? :)

**Comment by sydow** [comment]
I increase the probability of it being in the builtin to 100%. When we changed ints to be of arbitrary size, we of course had to change integer literals to be strings of arbitrary length. To convert long strings to big integers, I just relied on a function in BSDNT to do that. And I didn't think of the fact that this function expects decimal notation... I will see what to do.

**Comment by plajjan** [comment]
@sydow nice! Also add a test case maybe?

**Comment by plajjan** [comment]
@ddjoh you now have access to open branches on this repo, so when you encounter an issue, you can add a test case right away for it. In test/ directory there are a number of `_auto` directories, preferably place a test file in one of thos, like `builtin_auto/test_arithmetics.act`. It'll be picked up automatically by the test harness. Leave it failing on a branch and the fix can then be placed on that branch to prove it works...

if there's no directory that is particularly suitable, we have `test/regression_auto` which is the kitchen sink...

**Comment by plajjan** [comment]
@ddjoh I added so you can push branches here. When you encounter a bug, feel free to add a test for it! See tests/ directory. In particular ones that end with _auto. You can just drop new files in there and they will be run. Or drop it into an existing file if that looks more suitable!
