### ISSUE TITLE
Arithmetic mixups

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1074]
### Acton Version

0.13.0.20221108.1.18.56

### Steps to Reproduce

Run this program:
```
#!/usr/bin/env runacton
import random

actor main(env):
    a = 10000
    b = 20000
    c = 200

    print("a:", a)
    print("b:", b)
    print("a/c:", a/c)
    print("b/c:", b/c)
    r = random.randint(int(a/c), int(b/c))
    r2 = r * c
    print("random:", r)
    print("random2:", r2)

    await async env.exit(0)
```

### Expected Behavior

```
a: 10000
b: 20000
a/c: 50
b/c: 20000
random: <some random number>
random2: <the random number multiplied by 200>
```

### Actual Behavior

```
a: 10000
b: 20000
a/c: 50
b/c: 20000
random: 18700
random2: 18700
```

- b/c is all wrong, 20000/200 is not 20000
- computing r2 based on the random number r multiplied by 200 should mean it is different from ` r` but computing `r2` influences the value of `r`!?

Not sure if this is a compiler thing or a builtins thing? Assigning to both @nordlander and @sydow so you both can give your take on it :)

**Comment by sydow** [comment]
Fixed by #1076
