### ISSUE TITLE
Type inferencing cannot solve union of (None, int) while (None, str) works

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#110]
### Code / what did you do

I tried this code:

```Acton
def foo():
    if 1 == 3:
        return None
    return 3

actor main(env):
    await async env.exit(0)
```

### Expected outcome
It should compile! The type checker should understand that the return value is a union of (None, int) or maybe that's a "maybe int".

### Actual outcome

Trying to compile, I get:

```
../../dist/actonc union-none-int.act --root main

******************** Type error
Cannot solve 'w$18' : 'T$4' (__builtin__.Number), None < 'T$4', 'T$4' < 'T$3'
make: *** [Makefile:22: union-none-int] Error 1
```

If I change the program to return a string instead, it will work, like so (note the quotes around `3` in the return):
```
def foo():
    if 1 == 3:
        return None
    return "3"

actor main(env):
    await async env.exit(0)
```

### Meta
This is on the currently latest version of the main branch
`actonc --version`:
```
acton 0.4.2.20210820.11.49.39
```

**Comment by nordlander** [comment]
What a coincidence! I found this bug myself earlier this morning :-)

And the fix is traightforward, coming up...

**Comment by plajjan** [comment]
This is fixed through a recent commit. Closing.
