### ISSUE TITLE
Poor performance of compiler_rt udivmod (from zig cc compiler_rt)

### ISSUE THREAD

**Issue by sydow** [actonlang/acton#1101]
The udivmod implementation in zigs compiler_rt seems to perform rather poorly. It is in turn used by BSDNT in various situations. For example when we invoke zz_get_str when trying to print an int.

*The following is the original issue opened on poorly performing int printing of strings, which has subsequently been diagnosed to be poor performance of udivmod*

Consider the following program:
```
def printint(n):
    digs = []
    while n > 0:
        n,r = Integral.__divmod__(n,10)
        digs.append(str(r))
    digs.reverse
    print("".join(digs))

actor main(env):
    n = 10**8000
#    printint(n)
    print(n)
    env.exit(0)
```
It runs in 220 milliseconds on my computer; all time is spent in conversion/printing. If I comment out the print line and instead use the printint function defined in the file, the whole thing takes 40 milliseconds. And printint says in Acton what zz_get_str says in C, so this is very difficult to understand. I have written also a C  program that is exactly like this one, and using zz_get_str, and in runs in less than 40 milliseconds.  I would assign this to myself, but I have spent quite some time bug searching, so any ideas are welcome.
 
The following is a flame graph of the above program showing how almost all time is spent in udivmod:
![2022-11-14-141246_2391x612_scrot](https://user-images.githubusercontent.com/841628/201669027-12437b0b-4010-4026-a587-df32f6a9eb51.png)

**Comment by plajjan** [comment]
I believe I have identified one factor. Programs compiled with `zig cc` appear to be significantly slower than those compiled with gcc. Here I've hacked up actonc so I can specify which cc to use:
```
kll@Boxy:~/terastream/Programming-Language-Benchmarks/bench/algorithm/edigits$ ~/terastream/acton/dist/bin/actonc 1.act && time ./1 30000 > /dev/null
Building file 1.act
  Compiling 1.act for release
   Finished compilation in   0.383 s
Building executable /home/kll/terastream/Programming-Language-Benchmarks/bench/algorithm/edigits/'1'

real	0m3.279s
user	0m3.284s
sys	0m0.012s
kll@Boxy:~/terastream/Programming-Language-Benchmarks/bench/algorithm/edigits$ ~/terastream/acton/dist/bin/actonc 1.act --cc $(which cc) && time ./1 30000 > /dev/null
Building file 1.act
  Compiling 1.act for release
   Finished compilation in   0.360 s
Building executable /home/kll/terastream/Programming-Language-Benchmarks/bench/algorithm/edigits/'1'

real	0m0.147s
user	0m0.150s
sys	0m0.004s
kll@Boxy:~/terastream/Programming-Language-Benchmarks/bench/algorithm/edigits$ 
```

note how I don't have to rebuild the entire acton system, like builtins, RTS etc. It's all compiled with zig just like today, but I change the compiled used to build my test program here to the system cc (which is gcc on my machine) and the program runs 30x as fast.

So if you are comparing something compiled via acton vs something you build separately, then this could be an influencing factor.

At the end of the day I think it's clang / LLVM that's generating the final executable code, but zig must be influencing something before that, perhaps just some arguments to clang, which makes it run much much slower.

**Comment by plajjan** [comment]
Just as another datapoint, for the spectral-norm program it doesn't make much of a difference at all:
```
kll@Boxy:~/terastream/Programming-Language-Benchmarks/bench/algorithm/spectral-norm$ ~/terastream/acton/dist/bin/actonc 1.act && time ./1 500
Building file 1.act
  Compiling 1.act for release
   Finished compilation in   0.357 s
Building executable /home/kll/terastream/Programming-Language-Benchmarks/bench/algorithm/spectral-norm/'1'
1.274224116

real	0m3.482s
user	0m3.110s
sys	0m1.301s
kll@Boxy:~/terastream/Programming-Language-Benchmarks/bench/algorithm/spectral-norm$ ~/terastream/acton/dist/bin/actonc 1.act --cc $(which cc) && time ./1 500
Building file 1.act
  Compiling 1.act for release
   Finished compilation in   0.314 s
Building executable /home/kll/terastream/Programming-Language-Benchmarks/bench/algorithm/spectral-norm/'1'
1.274224116

real	0m3.106s
user	0m3.004s
sys	0m1.062s
```

I think I should commit this `--cc` argument to make it easier to experiment!

**Comment by plajjan** [comment]
Here's a flamegraph

![2022-11-11-154009_1496x496_scrot](https://user-images.githubusercontent.com/841628/201365848-e91af8c1-6882-4a72-af97-28df4b89e709.png)

pretty much all the time is spent in compiler_rt.udivmod, which I presume to be zigs compiler_rt, so perhaps it's just a dang slow implementation. At this point I'm not sure that what I'm talking is a general problem, the slowness your observing could be unrelated. I should open a separate issue for "my" performance issue...

**Comment by plajjan** [comment]
As per @sydow wish in an email thread, this issue has been converted to track the poor performance of udivmod in zigs compiler_rt. I also added in a flamegraph to show it for this particular performance.

Upstream bug is https://github.com/actonlang/acton/issues/1101

**Comment by plajjan** [comment]
Upstream has fixed this and we have since pulled in a newer version of zig, so closing.

@sydow already fixed our use of bsdnt to radically reduce the number of calls to udivmod, thus effectively working around the issue but even for some other program where udivmod is still used a lot, it should now work well! Closing.
