### ISSUE TITLE
Failure in test_time.act

### ISSUE THREAD

**Issue by sydow** [actonlang/acton#1102]
### Acton Version

0.14.0.20221111.12.5.37

### Steps to Reproduce

run make test

### Expected Behavior

success

### Actual Behavior

I hope I haven't messed up with branches in git now, but as far as I can see
- the command line argument provided by test.hs is in milliseconds
- the test in stdlib/test_time.act expects an argument in seconds.

**Comment by plajjan** [comment]
@sydow can you please include the output from your make test run?

I cannot reproduce this, nor can CI, since we would not be able to merge anything if this was consistently broken....

**Comment by plajjan** [comment]
I mean, you might be correct with regards to arguments from test.hs and expected input, but at least I don't get a test failure when I run this..

**Comment by sydow** [comment]
Well, I just did a hard reset in git and now I don't get the error in make test. I don't know how this could be and when I look at the test program test/stdlib/test_time.act and the command line generation in compiler/test.hs I still think that the test should fail.

**Comment by sydow** [comment]
The problem is understood.

The test is wrong. The commandline will be (roughly) 1000 times larger than what you compare with, because of the bug I explained in the bug report. Thus diff in function check in test_act.act will be a large negative number. In check you test only "if int(diff) > 5" so large negative differences will be OK.

But I had also created a bug. I wrote a C function to replace zz_get_str and thus to fix #1101.  That function worked fine, and was fast. But it had a bug which I hadn't noticed: as a side effect when printing negative numbers, it negated them(!). So in check when diff was printed before the test, it negated this erroneous large negative number and made it positive and the test failed.

So, when I got the test case bug before pushing my new print function, I (stupidly) scrutinized the test case rather than my code. I found the bug in the test and thought that was it...

I was also wrong in my reply yesterday afternoon. I claimed to be in main and get the bug. I was, but I has committed my print function in main, rather than in the bug-fixing branch for #1101. Sigh...

I  will fix the bug in my print fuction (and test it a bit more...) but leave to Kristian to fix the test.

**Comment by plajjan** [comment]
Ah ok. Should check so the diff is "just enough".

Feel free to fix if you want, no prestige in "owning" code or anything here... :) 

Guess we should also check the other time functions so we cover that other bug you noticed the other day...

**Comment by sydow** [comment]
I could fix it, but there is a design choice: is the intention to say that a diff of up to five seconds is OK? I guess 5 milliseconds is a bit tight?

**Comment by sydow** [comment]
Fixed by #1104.
