### ISSUE TITLE
Type inference errors

### ISSUE THREAD

**Issue by sydow** [actonlang/acton#1230]
### Acton Version

0.14.2.20230331.12.2.13

### Steps to Reproduce

For each of the following files f.act in the acton test suite, run 
```
actonc f.act --types
```

and/or 
```
actonc f.act --tempdir .
```
to save the interface file as out/types/f.ty

and then look at its contents:
```
actonc doc --signs out/types/f.ty
```
In each case the compiled file can be run with correct result and exits with exit code 0, but types displayed and saved in the interface files are wrong.

1. test/builtins_auto/builtin_functions.act

The file contains
```
def even(n):
    return n % 2 == 0
```
and the typing in the interface file is
```
even : [A(Eq, Integral)] => (None) -> bool
```
The type displayed by --types is
```
with:
    pure def even[T_4w] (W_43 : __builtin__.Eq[None], W_38 : __builtin__.Integral[None], n : None) -> __builtin__.bool:
```
Note the witnesses that None implements Eq and Integral.

2. test/regression_auto/103-dict-of-int

The file contains 
```
def foo():
    a = {"a": 1, "b": 3}
    return a
```
and the typing in the interface file is
```
foo : [A(Mapping[str, None]), B(Number)] => () -> None
```
The typing displayed by --types is
```
with:
    pure def foo[T_12, T_5] (W_13 : __builtin__.Mapping[None, __builtin__.str, None], W_6 : __builtin__.Number[None]) -> None:
```
Again we see erroneous witnesses.

3. test/regression-auto/110-union-none-int.act

The file contains 
```
def foo():
    if 1 == 3:
        return None
    return 3
```
and the typing in the interface file is
```
foo : [A(Number)] => () -> ?None
```
Typing displayed by --types is 
```
with:
  pure def foo[T_11] (W_12 : __builtin__.Number[None]) -> ?None:
        if W_9.__eq__(W_7.__fromatom__(1), W_7.__fromatom__(3)):
```
Same thing again.

I have a couple of more examples, but I guess they all have the same origin. I stumbled on them while playing with CodeGen.hs to try to improve treatment of literals.

### Expected Behavior

Correct types...

### Actual Behavior

---

**Comment by nordlander** [comment]
Fixed by my recent merge to main!
