### ISSUE TITLE
Directly printing actor method return value results in unexpected `<$Msg object...>`

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#13]
The code:
```
actor Foo():
    def ping():
        return "pong"

actor main(env):
    print(Foo().ping())
    var a = Foo().ping()
    print(a)
    env.exit(0)
```

The output is:
```
<$Msg object at 0x7fbc41504200>
pong
```

whereas I would expect to just see:
```
pong
pong
```

**Comment by plajjan** [comment]
Discussed with @nordlander. Clearly a bug. For the interested, the reason this happens is that Acton supports synchronous and asynchronous calls to Actor methods. Assigning the return value of an actor method implicitly does a synchronous call, like
```
var a = Foo().ping()
```
whereas just calling a method and not doing anything with the return value, like:
```
Foo().ping()
```
will call the method asynchronously. We can also explicitly ask for asynchronous execution even when capturing the return value, like:
```
var a = async Foo().ping()
```
then `a` will be a message and we can later `await` on a to wait for the asynchronously called method to return a value and then proceed. What happens in this case is that the Acton compiler fails to realize that `print()` wants the returned value, so it is executed as an asynchronous call, meaning we get back a message reference. By the time print reads the returned value, it is just the message reference and not the actual value. We would need to await it first. We shouldn't need to do that explicitly though, it should default to running the call synchronously (and could potentially be overridden through the use of `async` although no one knows the use of doing that).

We need to realize this in the compiler, so classifying this as a compiler bug.

**Comment by nordlander** [comment]
I looked once more and realized this bug is still there, it's just that current test is no longer able to detect it. But changing the ping() method above to something not pure (for example by defining it as an `action def`) makes the error show up again. Reopening and investigating.

**Comment by plajjan** [comment]
Confirmed fix with new deactorizer.

```
kll@ThinkYoga:~/terastream/acton/test$ actonc --version
acton 0.12.0
compiled by ghc 8.10 on linux x86_64
cc: 0.10.0-dev.4460+14c173b20
kll@ThinkYoga:~/terastream/acton/test$ actonc regression_auto/13-print-async.act && regression_auto/13-print-async
Building file regression_auto/13-print-async.act
  Compiling 13-print-async.act for release
   Finished compilation in   0.950 s
Building executable /home/kll/terastream/acton/test/regression_auto/'13-print-async'
<$Msg object at 0x7f3f4c000cb0>
pong
kll@ThinkYoga:~/terastream/acton/test$ ../dist/bin/actonc regression_auto/13-print-async.act && regression_auto/13-print-async
Building file regression_auto/13-print-async.act
  Compiling 13-print-async.act for release
   Finished compilation in   1.014 s
Building executable /home/kll/terastream/acton/test/regression_auto/'13-print-async'
pong
pong
kll@ThinkYoga:~/terastream/acton/test$ 
```

Closing.
