### ISSUE TITLE
Bad CodeGen redefines variables from outer scope

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1390]
Given this program:
```
def foo():
    if 1 == 1:
        b = 0
    else:
        b = 1

actor main(env):
    await async env.exit(0)
```

CodeGen currently outputs:
```
B_NoneType toointQ_foo () {
    B_int b;
    if (ORD_B_int__eq__(((B_int (*) (B_Number, B_atom))toointQ_W_4->$class->__fromatom__)(toointQ_W_4, to$int(1)), ((B_int (*) (B_Number, B_atom))toointQ_W_4->$class->__fromatom__)(toointQ_W_4, to$int(1)))) {
        B_int b = to$int(0);
    }
    else {
        B_int b = to$int(1);
    }
    return B_None;
}
```

The b variable is correctly declared before the if/else but then in each if/else scope, the b variable is redefined, shadowing the outer one. Clearly, after the whole if/else stanza, b refers to an non-defined value. Very bad.

If we initialize b before the if, it works correctly.
```
def foo():
    b = 123
    if 1 == 1:
        b = 0
    else:
        b = 1

actor main(env):
    await async env.exit(0)
```

generated code:
```
B_NoneType toointQ_foo () {
    B_int b = to$int(123);
    if (ORD_B_int__eq__(((B_int (*) (B_Number, B_atom))toointQ_W_7->$class->__fromatom__)(toointQ_W_7, to$int(1)), ((B_int (*) (B_Number, B_atom))toointQ_W_7->$class->__fromatom__)(toointQ_W_7, to$int(1)))) {
        b = to$int(0);
    }
    else {
        b = to$int(1);
    }
    return B_None;
}
```

**Comment by plajjan** [comment]
@nordlander I suspect this has a quite simple fix. If so, can we maybe sneak it in at the head of the work queue? :)

**Comment by nordlander** [comment]
Consider it done! (Actually, it _is_ done :-))

— Johan

3 juli 2023 kl. 13:55 skrev Kristian Larsson ***@***.***>:

﻿

@nordlander<https://github.com/nordlander> I suspect this has a quite simple fix. If so, can we maybe sneak it in at the head of the work queue? :)

**Comment by plajjan** [comment]
@mzagozen FYI!
