### ISSUE TITLE
Bad return type from int hashable

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1415]
`/home/kll/terastream/acton/dist/base/builtin/int.c:461:23: warning: incompatible pointer types returning 'B_i64' (aka 'struct B_i64 *') from a function with result type 'B_int' (aka 'struct B_int *') [-Wincompatible-pointer-types]`

int.c around line 461:
```c
B_int B_HashableD_intD___hash__(B_HashableD_int wit, B_int a) {
    long sz = a->val.size;
    if (sz==0) return toB_i64(sz);
    unsigned long res = a->val.n[0];
    if (res > LONG_MAX || labs(sz) > 1) 
        return to$int(B_i64D_hash(toB_i64((long)res & LONG_MAX)));
    else
        return to$int(B_i64D_hash(toB_i64(sz<0 ? -res : res)));
}
```

Should probably always return int and not i64, right? @sydow please fix :)

**Comment by sydow** [comment]
Fixed by #1419.
