### ISSUE TITLE
Add variable sized integer / decimal type -  BigInt

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#146]
We should support arbitrary size / multi precision integers!

The current `int` is a signed integer (64) - instead it should be variable sized. The thinking is that Acton users, which are more likely to come from simple high level languages like Python, than from memory-managing languages like C or Rust, should pick the simple alternative by default and it is simpler if `int` is the arbitrary size one. If someone wants a fixed size integer, they can explicitly say `i64` etc. Similarly, `actonc` should only type infer `int` and never the fixed size ones (maybe there are exceptions to this, but at least we should prefer to type infer `int` so we never get wrap-around etc).

Related is #793, which is about adding some fixed size integers.

**Comment by plajjan** [comment]
After thinking some more about this, I'm leaning strongly towards that the default integer type in Acton should be the arbitrary size one. This will make Python people feel right at home. Picking a fixed size integer is a guessing game about the maximum value at run time and we cannot make a good guess. It will be completely arbitrary. The developer on the other hand might have an idea and someone who cares about speeds and understand integer sizes are probably knowledgable enough to write a type signature in the right place to force a fixed size int.

Further, I suggest the following naming:
- `int` - the variable sized integer
- `int32`, `int64` etc for the fixed size integers

We probably want to support all kinds of sizes, from 8 to 64 bits and both uint and int. Not because most people will need to use them in code, but because they are useful for specifying interfaces. Like we have been talking about rendering YANG models from type signatures and then it might be possible to restrict a leaf to be a uint8 for example.

**Comment by plajjan** [comment]
@sydow is this possibly something you'd be willing to work on?

There are a few bignum libraries out there. GMP arguably the most famous and likely fastest. I think we want something BSD Licensed. BSDNT https://github.com/wbhart/bsdnt/ seems like a fairly good choice.

There are others but BSDNT seems like the best of the bunch if we want to avoid GPL taunting. However, I think you are in a much better position than I to really judge which one fits us best.

**Comment by plajjan** [comment]
As for my previous comment on naming, I still think the arbitrary sized integer should be `int`. The fixed sized IMHO should be `i32` or `u16`, that is either i or u followed by the number of bits. We should probably support 8, 16, 32 and 64.

we can do this in phases, like rename current `int` to `i64` (which I guess it is in practice on our supported platforms), add the bigint `int` then add the smaller ones and unsigned ones...

**Comment by plajjan** [comment]
Also also I think we want even smaller things like single bits and stuff but we can push that into the future. Would be nice for pattern matching and stuff on single bits for building protocols.... Maybe doesn't require a type though?

**Comment by sydow** [comment]
I will have a look, but probsbly not before August, unless we get a very rainy July.
I have no expertise at all in licence questions; perhaps a bit more in bignums...

**Comment by sydow** [comment]
I am working with this and it does not seem difficult. But I would appreciate help with placing the bsdnt library as a git subtree at a suitable place in our hierarchy and do the necessary additions to the Makefile. Or, perhaps with some advice I could  do the git thing, but the Makefile is definitely beyond me...

Unfortunately, I will not be able to attend the meeting tomorrow. I will go to Gothenburg to visit my grandchildren.

**Comment by plajjan** [comment]
@sydow yes, I will help out with including bsdnt! FYI, I'm doing quite a large reorganization of library dependencies, so this will take a little while but we should get there... :)

**Comment by plajjan** [comment]
Fixed via #992. Closing.

**Comment by plajjan** [comment]
We have now written some programs using our shiny big ints and performance isn't always stellar. A fair portion of that is likely due to BSDNT vs others using GMP, which prompted me to revisit the licensing of GMP again... while my understanding of the topic quite likely has incrased, the result is unchanged; the GMP license introduces unreasonable costs on us or our users

We want to statically link applications to the largest extent possible for portability reasons and this is in practice not supported with GMP.

GMP is LGPL licensed. LGPL does allow static linking but requires that the program that is statically linked with a LGPL library is also provided so that it can be relinked with a (presumably modified) version of GMP. As far as I can tell, this not only taints Acton but also all users of Acton. That is, if Bob were to implement program foo.act and compile it into the `foo` executable which he distributes on the Internet, he must also provide all users of `foo` the ability to relink his application with GMP at a later point in time, thus he is left with the choice of:
- providing the program source `foo.act`
- providing `foo.o` and potentially other object files which make up his foo program, so that someone else later can link that with their own version of GMP

This is an unreasonable burden on Acton users so at the very least, it cannot be the default choice. I also looked into other bigint libraries but BSDNT seems to be the only one with a BSD license. It is such a pity that GMP started out this way.

It's not exactly good news, but at least we're not alone. Haskell also tries to compile static programs but makes an exception for GMP, which is dynamically linked, like it's pretty much the only lib that actonc is dynamically linked with (except for system libc):
```
kll@ThinkYoga:~/terastream/acton$ ldd dist/bin/actonc
	linux-vdso.so.1 (0x00007fffd51e5000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f02d2dd9000)
	libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f02d2d58000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f02d2a00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f02d2c79000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f02d2e12000)
kll@ThinkYoga:~/terastream/acton$ 
```

I found a couple of haskell links:
- original 18 year old ticket https://gitlab.haskell.org/ghc/ghc/-/issues/601 (migrated from trace to gitlab)
- some notes on replacing gmp: https://gitlab.haskell.org/ghc/ghc/-/wikis/replacing-gmp-notes
- since then I think GHC is taking a somewhat different approach, letting bigints haskell interface be fixed but support different backends, gmp being one

We too could support different backends and GMP could be one, which would then in all likelihood be dynamically linked. However, I am adamant about not introducing dynamically linked libraries per default though, so GMP cannot be our default. Since we have a fairly limited time budget I think we will continue with BSDNT for the foreseeable future. If someone comes across a chest of gold and we have some interest in fast arithmetics, we can revisit pluggable backends + GMP.

I also have a hope BSDNT or something will grow. It looks almost dead, so that's not likely.. but one can still dream...

**Comment by plajjan** [comment]
I should add this reference https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic

> Does the LGPL have different requirements for statically vs dynamically linked modules with a covered work? ([#LGPLStaticVsDynamic](https://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic))
>
>    For the purpose of complying with the LGPL (any extant version: v2, v2.1 or v3):
>
>    (1) If you statically link against an LGPLed library, you must also provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application.
>
>    (2) If you dynamically link against an LGPLed library already present on the user's computer, you need not convey the library's source. On the other hand, if you yourself convey the executable LGPLed library along with your application, whether linked with statically or dynamically, you must also convey the library's sources, in one of the ways for which the LGPL provides.

**Comment by sydow** [comment]
Hi Kristian,

I would like to contribute with some more positive news. I think that the main problem we have had with BSDNT is with conversion to strings. In the examples with pidigits that I sent you yesterday, conversion of the output for printing was a significant part of the execution time. I saw that you played also a bit with the edigits benchmark where the effect was even more extreme, since even bigger numbers were printed. For that example the Acton program required more than three seconds for 100 000 decimals, a task that the equivalent Python program did in 0.5 seconds.

I have now written a new conversion function which converts ints to strings in very little time. In the pidigits programs the final Root computation is not noticeable, and the edigits programs runs in 0.1 seconds for 100 000 decimals. 250 000 decimals takes 0.25 seconds, vs Python’s 2.4. No gcc flag to the compiler is necessary.

The pull request is under test in CI right now.

Björn
