### ISSUE TITLE
Add volatile

### ISSUE THREAD

**Issue by nordlander** [actonlang/acton#1503]
Add C keyword `volatile` to C variable declarations declared outside an exception handler but referenced inside it. Example:
```
def f():
   res = 0
   try:
       res = 1
       raise ValueError
   except ValueError:
       return res         # should return 1

```
Here the generated C code must prepend the declaration of `res` with `volatile`, in order to be insensitive to any representation tricks the C compiler might perform on the code inside the try branch.

**Comment by sydow** [comment]
In fact, the problem occurs also in situations like this:
```
def f():
   res = 0
   try:
       res = 1
       raise ValueError()
   except ValueError:
       pass
   return res         # should return 1
```
Here, res is not referenced in the handler but in code executed after handling the exception. This is the code pattern occurring in buildy.act and indeed in many code instances generated by the code transformations of loops, such as 
```
res = v0
for i in expr:
   <update res using i>
<use res>
```
which is transformed to
```
res = v0
iter = expr
try:
   while True:
       i = next(iter)
       <update res using i>
except StopIteration():
   pass
<use res>
```

**Comment by nordlander** [comment]
Hmm. So this means we need to mark more variables as volatile: the intersection of those written in the `try` head and those read in the `except` handlers or in _any code that may run after such a handler_. Figuring out exactly what code may succeed a handler might be tricky in the presence of `break`, `continue` and nested `try` statements, but I guess a safe approximation would be to intersect with all variables read somewhere else than in the `try` head. That set should still be small because of the "written in the `try` head" requirement. Does this make sense?
