### ISSUE TITLE
Support conversion from hexadecimal number to `int`

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1507]
I don't think we have a way of taking a string containing a number in hexadecimal form and convert it into our `int`. We should have something builtin, either like Python's `int("1A", 16)` or something else.

@sydow or have I missed something? Is there a way? :)

**Comment by sydow** [comment]
Hi,

I think the way to go is Python’s — but not until we have parameters with default values working. Otherwise, we’ll get more “Positional element not found”.

Björn

**Comment by plajjan** [comment]
@sydow hah, yes. I agree completely, we'll wait for default args!  :)

It's hopefully not too long now... =)

**Comment by plajjan** [comment]
Since we now have default arguments, we can proceed with this one! @sydow do you wanna put it at the end of your todo? :)

**Comment by sydow** [comment]
Yes, I will do it.

But perhaps one should think a bit about design issues first. Maybe Python doesn’t have the optimal solution.

First, we can note that Python, like many other languages, supports integer literals in decimal (123), hexadecimal (0x12ac), octal (0o765) and binary (0b1101) notation. For no good reason Acton does not support the binary version; this could easily be fixed, if found useful. For even less reason there is a bug in Acton’s support for octal digits (it transfers directly the literal 0o765 to C, which is wrong; the correct C version is 0765)... We can also note that in Python 0765 is a syntax error, while in Acton it is accepted and treated as a decimal integer. This is, I think, as it should be.

Now to translation from strings. We want to do this using the int (and i64,…)  constructor. In decimal notation, it is straightforward: int(“123”). For other bases, Python uses a second argument which defaults to 10. So int(“12ac”,16) converts from hex notation; here the ‘0x’ prefix can be used, so int(“0x12ac”,16) is the same, with redundant info that the string is hexadecimal. For octal and binary, the situation is analogous. This raises several questions:

- Why not allow int(“0x12ac”) to convert from hex without the second parameter? In Python this raises

ValueError: invalid literal for int() with base 10: ‘0x12ac’

In the same way, we could allow for octal and binary strings with the corresponding prefixes.

- Is the second parameter needed (I know that I suggested waiting for optional parameters to implement this)? There are both pro and cons arguments:
   + with the second parameter we can allow arbitrary base, at least up to 36, if we follow Python and use decimal digits and English letters as digits. But who uses translation from string literals in base 13 or 21?
   - In Python the second argument is only allowed to appear if the first argument is a string. This is a strange restriction, which is ugly to me.

So I tend to suggest that we don’t introduce any second parameter at all, but allow ‘0x’, ‘0o’ and ‘0b’ prefixes to do translation of hex, octal and binary strings to integers. What do you think?

**Comment by plajjan** [comment]
@sydow agree with most of what you say. While I support your proposal of allowing things like `int("0x12ac")` I still quite like the idea of keeping the second argument to allow for arbitrary base, as you mention, but also to make it more explicit. The input value might come from somwehere where we know it is in base 16 but it doesn't have a `0x` prefix - it seems cleaner to do `int(a, 16)` than `int("0x" + a)`. It could be argued it is then redundant, but I think that's OK, we'd just have to check so `int("0x12ac", 9)` would yield an error since `0x` is not base 9.

**Comment by sydow** [comment]
This seems to be a not very important question, but let’s talk briefly about it on today’s meeting. 

I prefer to avoid the second argument but am willing to implement it. But I would like to 

- get to know the existence of at least *one* application where one needs to convert strings in a base different from 10, 2, 8 or 16 to an integer. And here I don’t count the math exercise “convert the number 13423 in base 5 to base 10”. This is a worthwhile exercise for a student to understand representation in different bases, but to gain understanding they should either do calculations by hand or write the code needed to do the conversion.

As far as I can see there is no builtin Python function to convert an int to a string in arbitrary base, just 10, 2, 8 or 16 (str, hex, oct and bin)? Does this say anything?



- understand why you think that int(a,16) is cleaner than int(“0x”+a) when a is a string of hexadecimal digits.  

One can also note that in Python the functions bin, oct and hex do return strings with base prefix. I think this is a good, clean design; both literals and string versions of integers carry their base with them.

**Comment by sydow** [comment]
Following today’s discussion I propose to do the following, which take the objections raised in the meeting into account. I just want to add one comment, which I didn’t think of immediately when it was raised today. The objection was that one would not for efficiency reasons want to create a new string “0x”+a if we have a very long string, i.e. from some file with thousands of hex digits. I don’t think this is plausible: you may very well have such a file and want to check it for correctness in some way, but you most certainly will NOT want to convert it to an int!  If the file has 10000 digits you would get a number of size around 10^12000 which you can’t do anything with. I still believe that for any practical uses of this constructor time or space efficiency is of no concern in choosing between int(‘0x’+a) and int(a,16).

Anyhow, let's add a second parameter base with default value 10 to the constructors for int types.

A user may or may not provide prefixes ‘0x’, ‘0o’ or ‘0b’ in the first (string) argument. If a prefix *is* provided and the second argument has the default value 10 (probably because the user omitted it), then the prefix takes precedence.

Examples:

int(“123”) gives 123

All the following give 0x123, i.e. 291:
int(“0x123”) 
int(“123”, 16)
int(“0x123”, 16)
int(“0x123”, 10) 

int(“0x123”, 8) gives a ValueError.

All values of base except 10, 2, 8, 16 gives a value error in the first implementation, but the  implementation will be dons so that there is no penalty if we want to add arbitrary bases later.

**Comment by plajjan** [comment]
The one thing that sticks out is
```
int(“0x123”, 10) = 0x123 / 291
```

I think you are suggesting this because 10 would be the default value for the second argument, so `def int(val: str, base: int=10)`, right? And thus, we cannot differentiate between when base is not set and when it is explicitly set to 10. Doesn't it make more sense to think of it as an explicit base, so we have `def int(val: str, base: ?int)`. The implicit base is still 10, so when base arg is None, then we still presume the string is in base 10 (unless it has a prefix). But if base is set to anything, it will take precedence and if the value string has a prefix that differs from the explicit base argument, it will return an error?

**Comment by sydow** [comment]
Of course you are right. Thanks!

**Comment by plajjan** [comment]
It's possible to search on github for uses of int with a weird base. This searches for base 9: https://github.com/search?q=%2F+int%5C%28%5B%5E%2C%28%29%5D%2B%2C+*9%5C%29%2F+language%3APython&type=code - update the query to search for others (there are so many cases of 2, 8, 10 & 16 that I find it easier to explicitly search multiple times for other numbers). From some quick skimming there seems to be use of bases other than 2, 8, 10, 16 although many of them are related to coding competitions, or weird hacks... but I think some of them are valid use cases. Perhaps we should spend a little more time browsing this to gain a better understanding...

**Comment by sydow** [comment]
This is fixed by #1644.

**Comment by plajjan** [comment]
Cool, that was quick! Nice @sydow =)
