### ISSUE TITLE
Division by 0 leads to some busy loop -> high CPU usage

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1521]
### Acton Version

0.16.0.20230930.0.55.21

### Steps to Reproduce

```python
actor main(env):
    3 / 0
    env.exit(0)
```

### Expected Behavior

An divide by zero exception?

### Actual Behavior

Programs hangs with 100% CPU usage.

**Comment by plajjan** [comment]
@sydow / @nordlander I note that float divide by zero returns 'inf'. Surely we want to mimic Python and do exceptions for floats and all integer types, right?

**Comment by sydow** [comment]
With exceptions properly working I think that integer division by zero should raise an exception. For floats I am not as convinced. In the IEEE standard division by zero has a well-defined value and there are algorithms that make use of it.

**Comment by plajjan** [comment]
Ok, interesting...

Well given your comment and today's conversation I think we should diverge from python and join the gang of /0=inf!
