### ISSUE TITLE
NoInfo 86 Type Error

### ISSUE THREAD

**Issue by ciaran2** [actonlang/acton#1555]
### Acton Version

 0.17.0.20231012.10.19.40

### Steps to Reproduce and Observed Behavior

This snippet in the acton-streamer repo https://github.com/dt-terastream/acton-streamer/blob/1aad5ac850ae5903306fa3bce5d6df39bed0b42a/src/acton_streamer/main/main.act#L722 triggers a "NoInfo 86" type error at compile time.

Removing the line `_get_xml.children.append(_curr_node)` allows compilation to proceed without issue.

It's unclear to me what the origin of the type error is in this case because it should be appending an `xml.Node` to a `list[xml.Node]` and more minimal reproduction of the case compiles without issue.

### Expected Behavior

It would be helpful for the compiler to more clearly indicate the nature of the type error in this case.

**Comment by plajjan** [comment]
The error
```
kll@Boxy:~/terastream/acton-streamer$ actonc src/acton_streamer/main/main.act 
Building project in /home/kll/terastream/acton-streamer
  Compiling tsdb/http.act for release
   Finished compilation in   0.422 s
  Compiling tsdb/m3.act for release
   Finished compilation in   0.119 s
  Compiling acton_streamer/common/utils.act for release
   Finished compilation in   1.139 s
  Compiling acton_streamer/common/mod.act for release
   Finished compilation in   0.876 s
  Compiling acton_streamer/common/io.act for release
   Finished compilation in   0.047 s
  Compiling acton_streamer/net/netconf.act for release
   Finished compilation in   0.379 s
  Compiling acton_streamer/nsoapi/proto.act for release
   Finished compilation in   0.645 s
  Compiling acton_streamer/nsoapi/conf.act for release
   Finished compilation in   0.102 s
  Compiling acton_streamer/nsoapi/channel.act for release
   Finished compilation in   0.022 s
  Compiling acton_streamer/nsoapi/cdb.act for release
   Finished compilation in   0.625 s
  Compiling acton_streamer/nsoapi/cdb.act for release
   Already up to date, in    0.000 s
  Compiling acton_streamer/nsoapi/schema.act for release
   Finished compilation in   4.224 s
  Compiling acton_streamer/nsoapi/conv.act for release
   Finished compilation in   0.123 s
  Compiling acton_streamer/nso/subscriber.act for release
   Finished compilation in   0.738 s
  Compiling acton_streamer/main/config.act for release
   Finished compilation in   0.261 s
  Compiling acton_streamer/nso/subscriber.act for release
   Already up to date, in    0.000 s
  Compiling acton_streamer/nsoapi/maapi.act for release
   Finished compilation in   0.957 s
  Compiling acton_streamer/nso/writer.act for release
   Finished compilation in   1.936 s
  Compiling acton_streamer/nso/writer.act for release
   Already up to date, in    0.000 s
  Compiling acton_streamer/nsoapi/maapi.act for release
   Already up to date, in    0.000 s
  Compiling acton_streamer/nsoapi/schema.act for release
   Already up to date, in    0.003 s
  Compiling acton_streamer/tsdb/writer.act for release
   Finished compilation in   0.162 s
  Compiling acton_streamer/main/main.act for release

ERROR: Error when compiling acton_streamer.main.main module: Type error
NoInfo 86
kll@Boxy:~/terastream/acton-streamer$ 
```

**Comment by plajjan** [comment]
The problem here is that _get_xml is `?xml.Node` since it is defined that way in https://github.com/dt-terastream/acton-streamer/blob/1aad5ac850ae5903306fa3bce5d6df39bed0b42a/src/acton_streamer/main/main.act#L693
```python
    def _update_get_params(get_path: Keypath):
        _get_xml: ?xml.Node = None
        _is_action = False
        _schema_path: ?SchemaPath = None
...
```
and then you try to append to it. I know that you have assigned to it, so in this scope _get_xml is guaranteed to be a non-optional type, but the compiler doesn't get that.

A minified example is:
```python
actor main(env):
    def test():
        foo: ?list[int] = None
        foo = [1, 2, 3]
        if foo is not None:
            foo.append(4)
            print(foo)
    test()
    env.exit(0)
```
this code works because I do the None check of foo before appending to it and printing. @ciaran2 so just do the equivalent in your code (I tried adding `if _get_xml is not None` on line 724 and it works).

Now, what do we want the error message to say for cases like this? I'm trying to understand how we categorize this, I think, based on what the old error message used to say:
```
kll@Boxy:~/terastream/acton/foo$ /usr/bin/actonc src/foo.act 
Building project in /home/kll/terastream/acton/foo
  Compiling foo.act for release

ERROR: Error when compiling foo module: Type error
 5:13-18
  |
5 |        foo.append(4)
  |            ^^^^^^
Cannot infer W_18 : ?__builtin__.list[__builtin__.int].append < T_19
```
that foo can be of a type (None) that does not have an .append() method, so type unification fails?

**Comment by ciaran2** [comment]
I think what makes more sense to me is simply complaining that as a `?list` it has no member/method `append`. That makes it clear that it isn't being treated as a `list` in the relevant scope.

**Comment by plajjan** [comment]
Closing this. Current error message is:
```
kll@Boxy:~/terastream/acton$ dist/bin/actonc examples/bar.act
Building file examples/bar.act
  Compiling bar.act for release

ERROR: Error when compiling bar module: Type error
 5:9-18
  |
5 |        foo.append(4)
  |        ^^^^^^^^^^
?__builtin__.list[__builtin__.int] does not have an attribute append
Hint: you may need to test if foo is not None
```

I think that's good enough. @sydow is continuing the work and so it'll only improve from here... although that reminds me we should actually add tests for these error messages.
