### ISSUE TITLE
What is the Acton idiomatic way of truncating digits in a float?

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1575]
How can we truncate the number of digits in a float? Going via a string is certainly one way, but it feels meh? Going via integer?

```python
a = 0.151
b = float("%.2f" % a)
c = int(a * 100) / 100
```

Should we have some more explicit function for float truncate? @sydow WDYT?

**Comment by sydow** [comment]
actor main(env):
    print (round(3.14159265,2))
    env.exit(0)
    

prints

3.14
31415926535000

**Comment by sydow** [comment]
Sorry, I missed to paste again the extended program with the line 

    print(round(31415926535,-3))

**Comment by plajjan** [comment]
Haha, that was easy. Thanks!

**Comment by sydow** [comment]
which exposes a bug!! :-) 

The intention with negative second argument to round is to round the number so that it ends with that number of zeros…
It should print 
31415927000

Back to work..

**Comment by plajjan** [comment]
Added a small example of float round() in https://github.com/actonlang/acton/pull/1576.
