### ISSUE TITLE
lstrip & rstrip with default arg broken

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1658]
```python
    def lstrip       (self, chars: str) -> str:
        NotImplemented
    def rstrip       (self, chars: ?str) -> str:
        NotImplemented
```

for some reason for lstrip the chars arguments is required. I don't think that was intentional as it seems the function is prepared for accepting a default / NULL argument. However, that does not work!

When I use rstrip or lstrip (after modifying __builtin__.act), the output is just completely blank!

```
actor main(env):
    a = " a b "
    print(a)
    b = a.lstrip()
    print(len(b))
    env.exit(0)
```

output:
```
 a b 
0
```

**Comment by plajjan** [comment]
@sydow I think you know best how to fix this! :)

**Comment by plajjan** [comment]
While we are on the topic, what should the default character set to strip away be? I suppose this was easy in an ASCII world but much trickier with unicode. I have a vague recollection that you've raised this question in the past @sydow. What does Python do?

**Comment by sydow** [comment]
The default in Python is to remove whitespace, which is prepared for in our str.c:

static struct B_str whitespace_struct = {&B_strG_methods,6,6,(unsigned char *)" \t\n\r\x0b\x0c"};

static B_str whitespace_str = &whitespace_struct;

There are some more strange Unicode code points that are classified as whitespace, but I think we ignore them for now.

lstrip seems to be seriously wrong, but should be easy to fix…
