### ISSUE TITLE
Add an optional keyword parameter init_capacity to constructors for lists, sets and dicts

### ISSUE THREAD

**Issue by sydow** [actonlang/acton#1702]
### Proposal

These three types are all based on the idea of allocating a small data structure initially, which, as need arises, can grow by allocating a new and bigger structure, followed by copying all data to the new structure. This is wasteful in situations where the programmer builds large structures and knows beforehand the final size (or has an estimate of that final size).

We typically start with size 5 and grow by doubling. So a list/dict/set of length 1 million will have intermediate copying to structures of size 10, 20, 40, 80, 160, 320, 640, 1280 ... and further doublings ten more times before we arrive at the final size.

The theoretical foundation for this policy is that the amortized complexity of inserting a large number of elements is still linear, but with a non-trivial constant factor. We should expect a substantial performance gain in many situations by adopting this simple measure.

Note that it is the capacity that is initialized, not the number which is reported by len, which is of course still 0. We only improve the potential for fast future growth.

The penalty for guessing wrong with the capacity is small; if you guess too little, you will have some doublings to do, if you guess too big, you will waste some space (until you delete an element, when this will be discovered and, if your guess was really wrong, the data copied to a smaller structure).

A particularly nice use case is when we want to copy, say, the values in a dict d to  a list vs. This becomes

vs = list(d.values(), init_capacity = len(d))

where we get exactly the correct size for the list at creation time. and no doublings will be necessary.  Similar examples apply to all kinds of transfer of data between objects of these classes. Note that iterators do not know how many elements they will emit before they stop iteration, but in these (and many other) cases, the programmer knows. 

The implementation of this is trivial; I estimate (generously) half an hour. I volunteer to do it.

I should add that you only profit from this when you grow the structure to its final size without intermediate deletions. When you delete an element from a list with very large capacity, it will be downsized to a small list...
### Motivation

It contributes to perforance enhancement in not too uncommon situations.

### Alternatives

--

**Comment by plajjan** [comment]
I have no objections!

**Comment by nordlander** [comment]
I agree too!

**Comment by sydow** [comment]
More experiments show that the real culprit is GC. Scanning large objects is too expensive even if they are cleared. Closing the issue.
