### ISSUE TITLE
after statement is broken, regression from simplified worker thread signalling

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#178]
The `after X:` statement is broken on main HEAD. I bisected and found that it is bf9597789acb6119ffe3b16bedce5c06a744b403 that introduces this breakage.

For example, in this program the test method should call itself after a second repeatedly until the variable i is large enough. It doesn't.
```
actor main(env):
    var i = 0
    def test():
        print("in test, i:", i)
        if i > 1:
            await async env.exit(0)
        i += 1
        after 1: test()
    test()
```

Is this in any way related to #170 and will be fixed through it or simple separate?

**Comment by nordlander** [comment]
It is very likely related to #170, in fact that would be my first guess for every piece of broken code that does some messaging within an actor constructor. Bug #170 is serious! Glad I found it, but somewhat embarrassed I allowed it to slip through in the first place.

**Comment by nordlander** [comment]
In fact it's not related to #170 but rather caused by my earlier change to how wakeup signals are sent to the worker threads. This has now revealed the fact that we never properly integrated the timer queue handling with the main IO event loop.

Will be done next!
