### ISSUE TITLE
Error messages: Location missing for hashable error

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1811]
This code:
```
def foo():
    a : ?str = ""
    b: dict[str, str] = {}
    b[a] = "hej"
```

gives us an error:
```
ERROR: Error when compiling ex24 module: Type error

?__builtin__.str must implement __builtin__.Hashable
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
```

It is missing location, which makes this rather hard to find in a larger program. 

I have added this as testcase test/typeerrors/ex24.act through #1810 

CC @sydow

**Comment by sydow** [comment]
Hej!

Jag har fixat #1811 och #1821  i branches fix-1811 och fix-1821 som har pushats. Tyvärr kan jag för tillfället inte köra test och merge eftersom jag inte kan logga in på GitHub. Hoppas detta fixas inom några dagar.

Björn
