### ISSUE TITLE
Should the RTS connect to multiple backend databases?

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#191]
When the RTS is used together with the distributed database backend, we connect to a single database node, which in turn gossips with the other servers.

Can we connect directly to multiple servers and use one or multiple in some form of redundancy setup, so that a compute node is not directly dependent upon a database node? Should we?

If so, the practical steps are just allowing some new argument to the RTS. Right now we have `--rts-ddb-host` and `--rts-ddb-port`. We could just let `--rts-ddb-host` be specified multiple time in order to connect to multiple backend servers. Mayhaps it should also support specifying the port per host, like `--rts-ddb-host localhost:12345` so we can specify the port per database (useful when running multiple database backends on localhost for development). We can still keep the `--rts-ddb-port` which can we be used if nothing else is specified.

**Comment by plajjan** [comment]
@aagapi I guess this is for you. Can and should the RTS connect to multiple database servers? Can we just run `        add_server_to_membership(ddb_host, ddb_port, db, &seed);` multiple times with different args to connect to multiple servers?

**Comment by aagapi** [comment]
Yes, this is desirable and it is already possible. One can just call add_server_to_membership() multiple times indeed. An example (although subsequent calls for 2nd and 3rd servers are currently commented out) can be seen in backend/actor_ring_tests_remote.c:600-602:
    add_server_to_membership(hostname, portno, db, &seed);
//    add_server_to_membership(hostname, portno+1, db, &seed);
//    add_server_to_membership(hostname, portno+2, db, &seed);
