### ISSUE TITLE
Add dict.pop()

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1989]
We discussed adding .pop() to dict / Mapping in our weekly meeting.

We said we wanted this:
```
protocol Mapping[A(Eq),B] (Container[A], Indexed[A,B]):
# NO EXCEPTIONS!!!
    get         : (A,?B) -> ?B
    pop         : mut(A,?B) -> ?B
```

And these functions should not throw any exceptions - they should return None if the key is not found.

**Comment by plajjan** [comment]
Hmm, so on second consideration, don't we want to have separate method for the get-with-default-value??

With the change as written in this issue and implemented in #1986, we end up having to None-check the result, even when we provide a default value - that seems suboptimal.

Like I feel the whole idea with a default value is that we know we get a non-optional value back. We can never statically enforce the type to be non-optional for a single get method where the default argument is optional, so I guess we need separate methods?

Something like this:
- `__getitem__(A) -> B` but throws `KeyError` if A does not exist
- `get(A) -> ?B` returns `None` if A does not exist
- `getdef(A, B) -> B` returns `B` if A does not exist

and similar for `pop` and `popdef` then !?

@sydow @nordlander @ddjoh WDYT?

**Comment by nordlander** [comment]
I agree, get with a default value is not the same as an optional get. One could merge the two by moving to the more elaborate signature
```
    get : [B(D)] => (A, Optional[D]) -> D
```
but that would require the planned support for unions as well as a lifted restriction in the constraint-solver. For later (perhaps).

The only thing about adding `getdef` is that _def_ probably reads as _definition_ to must Python programmers, not _default_. Maybe `getopt` could used instead?

**Comment by plajjan** [comment]
I wouldn't read too much into the name. Can't say I would immediately feel getopt is more intuitive than getdef. I mean, sometimes you just have to learn what something means and not what you might guess from a few characters.
