### ISSUE TITLE
Compiler bug: `Name X is not in scope`

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1992]
### Acton Version

0.24.1.20241119.9.21.7

### Steps to Reproduce and Observed Behavior

I think this should work:
```python
i = int

def foo(a: i):
    return 42
```

```
ERROR: Error when compiling aaa module: Compilation error

  |
4 |def foo(a: i):
  |           ^
Name i is not in scope
```

### Expected Behavior

i to be an alias of int

**Comment by nordlander** [comment]
This would require a type alias:
```
type i = int
```
Not supported yet, but on its way!

To elaborate: `int` and `str` are both class names that can be used to construct integer and string objects, at the same time as they are valid types that can be used in type annotations. But term expressions like `(int, str, 42)`, `[int, str]` and  `lambda a: (int(a), str(a))` are certainly not valid types, and there are many type expressions that don't qualify as run-time terms (like `(int)->str` and `dict[int,str]`).

So terms and types are two distinct syntactic domains in general, and only the class names count as members of both. And while there are more constructs that are indeed valid as both terms and types, we don't have any mechanism like a "type system" for keeping track of that intersection. So when we give a name to a term we only get a term, not a type, even in cases where the right-hand side would also qualify as a type:
```
tup = (int, str)
```
Conversely we need a way of giving names to types in their full syntax, which is what the `type` aliases will provide:
```
type tup = (int, str)
```
One thing to ponder whether we should allow these sets of names to overlap, that is, whether both the above bindings should be allowed at the same time. Which in turn is a way of asking whether a definition like the following would make sense:
```
def fun(x: tup):
   return tup
```
The first `tup` occurrence obviously refers to a type, so it's the type alias above that must be intended. And the second occurrence can only refer to a term, hence it must be `tup` as in the pair of constructor functions above.

Whether Joe Programmer can make sense of this distinction is a separate question, though, especially considering that there are names (of classes) that natively span the two syntactic domains.

Food for thought!

**Comment by plajjan** [comment]
#1693 is for tracking support for type aliases!
