### ISSUE TITLE
Default to using `main` as root actor

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#358]
If an acton source file defines an actor named `main`, we should detect that and use it as the root actor, thus automatically and implicitly building a binary executable!

**Comment by plajjan** [comment]
Our current default is an empty string (`""`). I tried just changing it to `root` which then fails when we try to compile `__builtin__.act`. I should have seen that coming! All libraries etc won't have a `root` actor.

We already have the concept of being in a project or not. If we are in a project, I think we can expect the project config file or the location of a source file to indicate whether a binary should be built or not. If we are not in a project, a.k.a. in script mode, then we should always build a binary, right? Thus, setting a default actor value like `root` makes sense, no?

**Comment by nordlander** [comment]
But isn't the point having a default available in the cases where we quickly want to build a binary? That is, when we're outside a project. I think it's correct to assume we want to build a binary in those cases, and a default root actor `main` sounds better in my ears than `root`.

But apart from this I believe we'll also want to preserve the ability to run the compiler on a particular file, just to check its static correctness if nothing else. So if the `--root` option turns into a default behavior we should perhaps add a "check-only" option to cover the special case. Why not call that option `--check`, with `-c` as a short-hand?

**Comment by plajjan** [comment]
Blargh, I meant to suggest we default to `main` as the root actor, not the value `root`... :) 

So I think we agree. When **not** in a project, we want to default to `main`.

Yeah, we can do a `--check` option, or I guess you could just do `--root ""` to get the current behaviour?

**Comment by plajjan** [comment]
@nordlander is there a way of parsing a file and inspecting the AST to determine whether there is an actor named `main`... or I mean, I presume that is possible, but how?

**Comment by plajjan** [comment]
We previously wrote in this issue that we should only do this outside of a project... I think that was simply because we focused on the simpler case outside of a project... but really, it doesn't make sense to restrict this, on the contrary, detecting a main actor and using it as root makes sense in a project too I think. It's like a sensible default, which we can then override in the project config.

**Comment by sydow** [comment]
This is implemented by #726 (except for --check).
