### ISSUE TITLE
Revamp deactorizer and nail down sync/async actor method call semantic

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#374]
This is a big one and already in progress, originally initiated by #13. Over time the deactorizer has become a bit of a patchwork and needs to be revamped to work with the current look of everything.

Multiple other issues likely boil down to this issue.

**Comment by nordlander** [comment]
As I suspected, there's more to our brilliant idea from earlier today than what first meets the eye :-)

If we want invocations of nominally asynchronous local methods to ultimately be detected at run-time, we must of course also be prepared to run those methods synchronously at the same callpoints. But in contrast to the asynchronous method wrappers, the real code of an actor method is a CPS-converted function, that can only be invoked if the caller supplies a continuation argument and lets the function return directly to the runtime system.

This means that if we want to pursue this idea we must start CPS-converting the asynchronous call sites as well. Do we want to do this? I'm hesitating, but I've also come to realize that my reaction is mostly emotional. We're already CPS-converting quite a bit and I actually have no logical reason to believe a few more continuations will make any noticeable difference to performance. It's also worth emphasizing that calling a CPS'ed ASYNC doens't have to imply checkpointing, we can still limit that activity to the observable await- & termination points if we want to.

And in any case, I don't see a reasonable alternative that also retains the conceptual simplicity of today's idea. Ok to go ahead?

**Comment by aagapi** [comment]
Yes, I also think the overhead of maintaining and executing continuations for these sites will be small relative to, for instance, checkpointing overhead. As long as the number of checkpointing points remains the same by this change I don't think it will make a major difference in performance, and the change is definitely worth it, as it will likely simplify the de-actorizer quite a bit and ultimately make things more uniform wrt method invocations. So I would say to go ahead with the change from this point of view.

**Comment by plajjan** [comment]
This was fixed through #1020. Closing.
