### ISSUE TITLE
Rename complx.h -> complex.h ?

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#397]
Is this just a misspelling or is it deliberate?

**Comment by nordlander** [comment]
Deliberate! Clang (or is it originally gcc?) seems to treat any file called "complex.h" in a very special way, which disrupts our intended use. Not sure if this should be called a compiler feature or bug, but Björn knows the details. Anyway, we found that simply renaming the file solved the problem so we preferred not to investigate any further.

**Comment by plajjan** [comment]
Hmm, could it be that it collides with the system complex.h? Though shouldn't they have different paths? Well anyway, let's not rename... but I'll add a quick note so future me won't get bugged by it again ;)

**Comment by nordlander** [comment]
My impression is that paths aren't considered when the compiler tries to identify the system header complex.h. Weird, but we can live ith it since the workaround is so simple.
