### ISSUE TITLE
On module version management

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#416]
If m1 and m2 depend on m3 but each require different versions, can m1 pass data to m2?

https://github.com/dtolnay/semver-trick

**Comment by nordlander** [comment]
Currently no, but in the system we've been sketching: yes!

The central feature is that when m3 is upgraded to a new version, any type names in the new version of m3 that are _not_ changed will semantically be treated as aliases to their namesakes in the old version.

The only catch is that we haven't really introduced type aliases yet...

**Comment by plajjan** [comment]
Maybe it's the same thing, but the way we talked about it we have focused on the transition from one version to another.

In this case I'm not talking upgrades. A library (m1) written by someone depends on m3 version 1. A second library m2 depends on m3 version 2. Now we write an app that uses the two libraries and we tie them together so data is passed from one to the other. This isn't a temporary transition but the permanent state of the system. Will it work?

Do you mean we would use the upgrade function to automatically and continously upgrade the data structures passed between the two? IMHO that seems different than the upgrade case. For one, it seems we also need downgrade capability.

**Comment by plajjan** [comment]
We should adopt content addressing and so the local names are not interesting. m1 can pass data to m2 if the type of the thing in m3 is unchanged. Otherwise it needs a conversion function in between!

**Comment by plajjan** [comment]
I'm going to close this in preference of tracking content addressing using #817.
