### ISSUE TITLE
Poor performance (timeouts?) in DDB when running in GitHub Actions

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#449]
We are seeing very poor performance when running our tests in GitHub Actions. RTS interacts with the DDB and we can see delays of 10 seconds, sometimes 30 seconds in the database overhead when running a continuation. It always or very often seems to be a multiple of 10 seconds, which brings ones mind to some form of timeout or similar timer value.

I'm unable to reproduce this locally on my machine - it only happens in GitHub Actions.

For example, see this job: https://github.com/actonlang/acton/runs/4730597179?check_suite_focus=true

We start up a DB cluster and then run the app. It takes ~53 seconds to run the app, I'd say with 3 seconds due to #94 and then 5*10 seconds - note how nicely the milliseconds line up.
```
./test_db.py --db-nodes 3 --app ./test_db
2022-01-06 18:31:07,940: test_db    INFO     -- Round 0
2022-01-06 18:31:07,940: test_db    DEBUG    Starting database servers
2022-01-06 18:31:07,942: test_db    DEBUG    Starting instance 1
2022-01-06 18:31:07,945: test_db    DEBUG    Using Membership info from Db0 as expected
2022-01-06 18:31:07,945: test_db    DEBUG    Membership info for Db1 is as expected
2022-01-06 18:31:07,946: test_db    DEBUG    Starting instance 2
2022-01-06 18:31:07,949: test_db    DEBUG    Using Membership info from Db0 as expected
2022-01-06 18:31:07,949: test_db    DEBUG    Membership info for Db1 is as expected
2022-01-06 18:31:07,950: test_db    DEBUG    Membership info for Db2 is as expected
2022-01-06 18:31:07,950: test_db    DEBUG    Starting application: ./test_db --rts-verbose --rts-ddb-host localhost --rts-ddb-replication 3
2022-01-06 18:32:00,968: test_db    DEBUG    Application exited successfully
2022-01-06 18:32:00,968: test_db    DEBUG    Stopping database servers
```

There are many more runs like this. @nordlander and I was debugging this yesterday and finally added debug printouts, you can see the full log from that here: https://pipelines.actions.githubusercontent.com/bUwiqcYfhKPXHyUKHtlkFhkGsW6SdFaboa5pvYlNyqiWfZ39Fd/_apis/pipelines/1/runs/812/signedlogcontent/2?urlExpires=2022-01-11T13%3A37%3A07.8471694Z&urlSigningMethod=HMACV1&urlSignature=2F7IyIjD1hSDZYkc4uOuawk1ZrOwzXhhiT4973eFuAk%3D

The timing output contains "TIME" and then either "actor" or "overhead", which is the time it took to run the actor continuation and then for the overhead of persisting state etc, which in the case of when using the DDB is naturally mostly spent interacting with the DDB. To sum up that log we see this:
```
kll@Boxy:~/terastream/acton$ egrep "TIME.*: [0-9]{8,}" ddb-slow.log
2022-01-11T13:33:30.9912485Z **RTS** ## TIME overhead -14: 10000880432
2022-01-11T13:33:54.2630125Z **RTS** ## TIME overhead -14: 10005617070
2022-01-11T13:34:47.5310249Z **RTS** ## TIME overhead -14: 30001239455
2022-01-11T13:35:07.5320355Z **RTS** ## TIME overhead -14: 30001109554
```
So there are 4 transactions that spend 10 or 30 seconds (times are in nanoseconds) in the overhead part. Running without the DB is always fast.

It took me way too long to realize it was even the database, partly because it is hard to get information from the RTS too and both @nordlander and I suspected my python test running script (which caused me to rewrite it multiple times with various approaches). Need better debug... I did add that RTS monitoring functionality a while back but it is mostly for realtime interactive use. In this case, when running in CI, we would need a different output form. I will try to address this separately!

Back to the database... I think the first step is to add enough instrumentation so that the DB can tell us what part is slow / where we have outstanding requests or similar. There might be something wonky with GH Action runners but we can't just point a finger and say "bad environment" - we have to be able to provide enough diagnostics that a normal use can understand that it is something about the environment that is broken. Like DNS? (it's always DNS!)

**Comment by aagapi** [comment]
Please check if this is fixed by commit:
https://github.com/actonlang/acton/pull/453/commits/09afd13049cc05bf85ce618c1ce2cf97c81d1df4
This fixes a possible race condition the DB client wait_on_msg_callback() function, that could trigger an RPC timeout when a quorum of servers manages to reply to a client request before the DB client on the RTS side got to call pthread_cond_timedwait on the message callback. As @nordlander pointed out, this is not entirely unlikely to happen on the CI environment.

**Comment by plajjan** [comment]
I rebased the debug branch we worked on, to include your patch, and after running it through CI... there are indeed no more problems like that happening!

I understood that this is the final fix, right? Like there's nothing we want to improve even further here? I suppose I'm a tad uneasy about this because it feels like we just reduced the gap and didn't close it completely, like it is still possible that this could happen if a server is fast enough? But maybe this is just the way things are when working in C - no real guarantees just probable enough. I'll try to get used to that idea ;)

I opened #452 for adding statistics, so no need to keep this issue around to track that. Seeing how there is nothing actionable left here, I'll close...

**Comment by nordlander** [comment]
I understood Andrei's proposed fix as a proper one, which entirely removes the possibility that db replies are lost/delayed. The core detail is to check the sought condition (the existence of a reply in this case) immediately after taking the protecting mutex, and skip the condvar wait if the result is already true. Airtight!

**Comment by plajjan** [comment]
Thanks for pointing out the core detail. I get it now and feel much better 😊
