### ISSUE TITLE
Database segfault

### ISSUE THREAD

**Issue by nordlander** [actonlang/acton#463]
I'm getting a segfault in the db client code when I try to run 'make test_db_app' in the test directory. It happens consistently during bootstrapping, in fact while committing the very first actor (env_actor) to the database.

I've determined the call chain to be

    remote_commit_txn
        close_client_txn
            get_client_txn_state
                skiplist_search
                    list->cmp

And the last call probably crashes because its first argument (x->forward[i]->key) is NULL.

I haven't tried hunting this down any further because I suspect the error might be something related to my environment -- after all, the main branch has passed the CI tests and 'make test_db_app' is one of them!

So it's definitely a local problem on my laptop and I'm mostly curious about what a NULL key in the scenario above might be caused by. @aagapi: any idea?

**Comment by plajjan** [comment]
FWIW, we are seeing intermittent failure on MacOS in the CI tests. The application dies with a segfault but I think it usually progresses a fair bit, like it doesn't die while committing the first stuff to the DB but rather runs some continuations etc. Could be related, or not at all related 🤷

**Comment by plajjan** [comment]
Fixed through #488. Closing.
