### ISSUE TITLE
TCP content should be bytearray

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#468]
For TCP connections we do `to$str` on the content (in env.c), which presumes that the content can be unicode decoded. I think sockets should return bytearrays instead.

**Comment by plajjan** [comment]
I feel this depends on #527.

**Comment by plajjan** [comment]
@sydow, now that you are into bytes, do you want to attempt to fix this one so we get bytes returned from TCP sockets rather than strings? :)

**Comment by sydow** [comment]
Yes, I will try. Or, I started to try... Is there any working example using sockets? I had a pair, client.act and server.act in directory acton/examples, but since then Env has changed. So I edited them and now they compile, but when run the server segfaults. I could go on and track what happens in $l$1lambda$__call__ in env.c, but it would be easier to have something that already works.

**Comment by sydow** [comment]
No problem with the examples. I will try your example.

Yes, bytes object have a parameter-free decode() method (since we only support utf-8).

**Comment by sydow** [comment]
The problem with my client/server example is a bug in builtin/env.c that makes programs that use stdin_install crash. For 
stdin the rhandler has type action(str)->None while for Connections it has type action(Connection, str)->None. The code on line 1398 in env.c treats both cases as the latter. One fix is to replace line 1398 by

                    if (fd==STDIN_FILENO)
                        fd_data[fd].rhandler->$class->__call__(fd_data[fd].rhandler, to$str(fd_data[fd].buffer));
                    else
                      fd_data[fd].rhandler->$class->__call__(fd_data[fd].rhandler, fd_data[fd].conn, to$str(fd_data[fd].buffer));

This makes the minimal test program

actor main(env):
   env.stdin_install(env.stdout_write)

work (as well as my programs). Should we do a separate fix of this before I start with bytes?

**Comment by nordlander** [comment]
> On 9 Jun 2022, at 14:31, sydow ***@***.***> wrote:
> 
> 
> The problem with my client/server example is a bug in builtin/env.c that makes programs that use stdin_install crash. For
> stdin the rhandler has type action(str)->None while for Connections it has type action(Connection, str)->None. The code on line 1398 in env.c treats both cases as the latter. One fix is to replace line 1398 by
> 
>                 if (fd==STDIN_FILENO)
>                     fd_data[fd].rhandler->$class->__call__(fd_data[fd].rhandler, to$str(fd_data[fd].buffer));
>                 else
>                   fd_data[fd].rhandler->$class->__call__(fd_data[fd].rhandler, fd_data[fd].conn, to$str(fd_data[fd].buffer));
> 
> This makes the minimal test program
> 
> actor main(env):
> env.stdin_install(env.stdout_write)
> 
> work (as well as my programs). Should we do a separate fix of this before I start with bytes?

Good idea!

-- Johan

**Comment by sydow** [comment]
I didn't look at error handlers. Line 1363 also needs to be changed by adding a Connection parameter.

Shall I do a pull request? (I don't know the rules...)

**Comment by nordlander** [comment]
> On 9 Jun 2022, at 15:07, sydow ***@***.***> wrote:
> 
> 
> I didn't look at error handlers. Line 1363 also needs to be changed by adding a Connection parameter.
> 
> Shall I do a pull request? (I don't know the rules...)

These changes belong together, I think. Could be part of the same pull request.

-- Johan

**Comment by plajjan** [comment]
Fixed in #663. Closing!
