### ISSUE TITLE
DB client API should not exit(0)

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#579]
bad bad!

https://github.com/actonlang/acton/blob/main/backend/client_api.c#L610

not sure if it needs to exit at all? but at the very least, exit with 1 or something, so we know something bad happened...

**Comment by aagapi** [comment]
It should not exit at all, as this is meant as an error msg handler for socket operations (such as attempting to write on a socket closed by the other end). In these cases, the RTS should not exit at all. I pushed a similar change yesterday in https://github.com/actonlang/acton/pull/574 (on the server side), so just remove the exit() altogether on the client side as well.
