### ISSUE TITLE
Improved treatment of hex escape sequences in strings

### ISSUE THREAD

**Issue by sydow** [actonlang/acton#658]
The improved implementation of strings recently added has (at least) one major problem: the following statement gives a compilation error:

   s = "\x48ello, world"
******************** Syntax error
 52:11-13
   |
52 |   s = "\x48ello, world"
   |          ^^^
"\x" must be followed by exactly two hexadecimal digits

For the moment we check that \x is followed by exactly two hexadecimal digits; otherwise we report an error.  We cannot just allow the above and use the string directly in C, since C allows for an arbitrary number of hexadecimal digits:

a.c:4:14: error: hex escape sequence out of range
  char* s = "\x48ello, world";
             ^~~~~
Here the 'e' as a third hex digit is purely accidental, but of course we cannot leave it as it is. One possible solution is to break strings after two hex digits so "...\x123..." is transformed to "...\x12" "3...". We must then avoid concatenating strings in Normalize.hs and rely on the C compiler's ability to concatenate strings.

Other solutions are possible, but this is what I thought of. Comments?

**Comment by plajjan** [comment]
@sydow your suggested solution sounds good to me! :)

**Comment by sydow** [comment]
The suggested solution above is implemented.
