### ISSUE TITLE
Generate function declarations for function type signatures in hgen stub mode

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#694]
```
def foo(a : str, b : int) -> Set[str]:
    return {"asdf", "kaka"}

bar : action(a : str, b : int) -> Set[str]
```

When we stub and --cgen the above, actonc will generate a C function for `foo` but not for `bar`, as it should. For `--hgen` we also do not generate a function declaration for bar, since it is not defined in the acton module.... but I think we should. While for the C function definition, the body of the function need to be written by the user, but the function prototype with argument and return types should always match the Acton type signatuer, right? So wouldn't it be better if we also generated the function declaratoin for `--hgen`?

**Comment by nordlander** [comment]
New take on this topic, see PR #706 (especially file test/regressions_auto/not_implemented.act).
