### ISSUE TITLE
A new kind of bug in type inference?

### ISSUE THREAD

**Issue by sydow** [actonlang/acton#711]
After introducing equality for lists and dicts I have noted some type bugs that I have not seen before: adding type annotations to code that passes the type checker makes it fail:

```
lst : list[int]
lst = list(range(10,14,1))

actor main(env):
   print(lst==[10,11,12,13])
   env.exit(0)
```
  
Without the type annotation on lst the file compiles, inferring type list[int] to lst, and can be run (writing True), but with the type annotation the type checker cannot solve the generated constraint set.

**Comment by nordlander** [comment]
Now fixed,
