### ISSUE TITLE
Improved error messages from the parser.

### ISSUE THREAD

**Issue by sydow** [actonlang/acton#732]
Anyone with some experience of compiling Acton programs have seen completely incomprehensible error messages. I plan to try to something about that, but progress needs EXAMPLES OF BAD ERROR MESSAGES. As soon as you see a bad error message, post it as a comment to this issue.

**Comment by plajjan** [comment]
Is this the kind of parser error messages you are looking for?
```
ERROR: Error when compiling foo module: Syntax error
src/foo.act:3:1:
  |
3 | def f():
  | ^
unexpected 'd'
expecting end of input or import statement
```
for this program:
```
def f():
    if a:
```
clearly, it's missing something at the end, but the error message rather points to the `d` on the `def ...` line, which is weird. I had this appear in a much larger program and it took me a while to figure out I had the indent wrong which screwed up a block of code but that came out as an error on the d in def, just like above. This was the minimal program I could write that reproduces that.

**Comment by sydow** [comment]
This is exactly the kind of error message I’m looking for… Thanks.

**Comment by plajjan** [comment]
@ddjoh given that you are likely the one doing most work using Acton now, if you see incomprehensible errors related to **parsing** of an Acton program, feel free to post examples here.

**Comment by plajjan** [comment]
I'm going to close this issue. I think it goes in general that when we find bad error messages we should open issues. I think those issues should be rather specific so that they are actionable.
