### ISSUE TITLE
Move lookup_a/aaaa into free but internal functions

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#776]
We want to be able to do DNS lookups in internal code, like when doing happy eyeballs for TCP connections. Having to first instantiate a DNS resolver actor which will then only be used for 2 lookups seems a bit much. If we just move the functionality in net.DNS.lookup_a to net._lookup_a() we can then also use that from net.DNS.lookup_a(), so no duplication of code.

It should only be possible to call this function internally, thus the leading underscore.

**Comment by plajjan** [comment]
Hmm, will this actually work? I have a vague memory that the compiler thinks the callback arguments will be `$Cont` when they really ought to be `$function`...

**Comment by plajjan** [comment]
Right, so as I remembered, just copying the DNS.lookup_a into _lookup_a, like so:
```
def _lookup_a(name: str, on_resolve: action(list[str]) -> None, on_error: action(str) -> None) -> None:
    """Perform DNS lookup for name of record type A
    """
    NotImplemented
```
.. the compiler thinks the signature is:
```
$NoneType net$$_lookup_a ($str, $Cont, $Cont);
```

When I think it should be:
```
$NoneType net$$_lookup_a ($str, $function, $function);
```

@nordlander am I right? Is the compiler wrong?

**Comment by nordlander** [comment]
Hmm, that’s wrong. I’d gave expected callback arguments of some bespoke subclass to $function but not $Cont.

Must look into that!

— Johan

9 aug. 2022 kl. 10:56 skrev Kristian Larsson ***@***.***>:

﻿

Right, so as I remembered, just copying the DNS.lookup_a into _lookup_a, like so:

def _lookup_a(name: str, on_resolve: action(list[str]) -> None, on_error: action(str) -> None) -> None:
    """Perform DNS lookup for name of record type A
    """
    NotImplemented


.. the compiler thinks the signature is:

$NoneType net$$_lookup_a ($str, $Cont, $Cont);


When I think it should be:

$NoneType net$$_lookup_a ($str, $function, $function);


@nordlander<https://github.com/nordlander> am I right? Is the compiler wrong?
