### ISSUE TITLE
make fails in clean repo

### ISSUE THREAD

**Issue by nordlander** [actonlang/acton#781]
Running make in a fresh clone of the main branch resulkts in a failure on MacOS (Big Sur) when the stdlib project is compiled:
```
cc stderr:
In file included from stdlib/out/types/time.c:1:
stdlib/out/types/time.h:2:10: fatal error: 'builtin/builtin.h' file not found
#include "builtin/builtin.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```
Running make -j repeatedly eventually succeeds, though.

Mysterious!

**Comment by plajjan** [comment]
It's quite mysterious indeed. I figured I had just missed the dependency on builtin/builtin.h but it's actually there already! (someone did consider a thing or two before writing the makefile!!)

I can't immediately spot where the error is...

**Comment by plajjan** [comment]
I mean a dependency on dist/builtin/builtin.h!
