### ISSUE TITLE
DB segfaults when killing app early

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#860]
in the test_db_app_resume_tcp_client test we run an Acton test program together with the DB, roughly:
- start up TCP server, counter=0
- start up DB cluster
- start TCP client app with DB, which connects to TCP server and check current value (0)
- sleep for a bit
- terminate app
- increase value in TCP server (1)
- start app again, which should now resume, retry the connection to the TCP server, note the correct higher value (1) and exit(0)

This works well in general however if we terminate the app before it has reached a "steady state", the app will segfault when being resumed.

On my AMD 5950X computer this happens when we sleep for 0.1 seconds, which happens to be what we are currently sleeping in `main`. In fact, it fails so much that even after adding the 5 retries for DB test (#853) it still fails. My machine is usually way faster than the CI runners so I'm guessing this mostly passes CI because they are slower and we terminate the TCP client test app earlier before it has reached some "bad state".

The desired outcome is two fold I believe:
- [x] rewrite tests to not rely on a arbitrary timer, instead looking at the output of the TCP client app to determine when it has reached some "steady state"
- [ ] attempt to induce segfaults, find root cause and fix! we should never ever crash no matter when we might be terminated!

**Comment by aagapi** [comment]
When trying to repro this, observed that the TCP client actor does not crash, but it actually blocks indefinitely, and the subprocess spawned by test_db.py fails with subprocess.TimeoutExpired, which causes the CI failure. During this process, the DB servers stay up, so the issue does not seem to be DB related, but the issue might be related with issue #908 , which seems libuv related. Created issue  #909 to track the test_app_resume_tcp_client blocking, #908 to track the test_app_resume_tcp_server crash, and the (possibly related) blocking that happens for processes recovering their timer queue in #907

**Comment by plajjan** [comment]
For the record, it 100% reproducibly segfaults. It does not time out for me. I should reattempt after some of these fixes have gone in...
