### ISSUE TITLE
Type error when attempting to set class instance member variable outside of __init__

### ISSUE THREAD

**Issue by ddjoh** [actonlang/acton#936]
### Acton Version

0.11.6.20220928.13.17.45

### Steps to Reproduce

Compile the following with `actonc build`
```
class Aa:
    x: int

    def __init__(self):
        self.x = 0

    def mutate(self):
        self.x = 1
```

### Expected Behavior

actonc build to successfully finish compilation

### Actual Behavior

actonc build responds with:
```
ERROR: Error when compiling act_test_1 module: Type error
 8:14
  |
8 |        self.x = 1
  |             ^
Cannot solve Self < 'T$15', 'T$15' < __builtin__.object, 'T$15' .x > 'T$16', Self < 'T$8', 'w$19' : 'T$17' < 'T$16', 'T$8' .x > 'T$9', 'w$18' : 'T$17' (__builtin__.Number), 'w$12' : 'T$10' < 'T$9', 'w$11' : 'T$10' (__builtin__.Number)
```

**Comment by nordlander** [comment]
Ah, a subtle issue! A class must inherit from `object` in order to be mutable, and the Acton default base isn't object but the even more primitive class `value`. So changing the header to
```
class Aa (object):
```
should do it!

**Comment by ddjoh** [comment]
Great, thanks!
