### ISSUE TITLE
Gossip protocol not gossipping added DB server to RTS

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#951]
### Acton Version

v0.11.7

### Steps to Reproduce

- start db1: `actondb -p 32000 -s 127.0.0.1:32001`
- start RTS: `examples/count --rts-ddb-host localhost`
  - default replication is 3 so this will result in a non-working setup since we only have 1 server
  - ideally we should have code in place so RTS hangs until we see quorum, but currently that doens't happen so RTS does process some stuff
- start db2: `actondb -p 32002 -s 127.0.0.1:32001`

### Expected Behavior

I expect RTS to be gossiped to from db1 that db2 has joined.

### Actual Behavior

db1 and db2 gossip and agree on a view which both install but this is never communicated or never shows up in RTS.

**Comment by aagapi** [comment]
Fixed in https://github.com/actonlang/acton/pull/968

**Comment by plajjan** [comment]
Confirmed fix, nice! :)
