### ISSUE TITLE
C lib wrapping: explain when something is sync vs async!

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#98]
I believe the following is true:
- modules with free functions (not in a class or actor) will always be synchronous
- methods on classes are also always synchronous, since they are really instantiated within an actor and everything within an actor is always synchronous
- modules that implement actors will default to the actor behaviour, which is that when an actor method is called without binding the return value, like `foo.bar()`, then it is called asynchronously, whereas if the return value is assigned, like `a = foo.bar()` then the actor method call is synchronous

@nordlander is the above true? Also realized while writing this, that this is not specific to when wrapping C libraries - this is the generic Acton sync behavior, but I guess it is somehow extra relevant to point out when implementing a library.

I know it is possible to explicitly do something async or sync by adding `await` / `async` keywords at the call site. Is it possible to change the sync/async behaviour by specifying something at the function definition? No, right? I think I've asked this before but have forgotten.

Should add this to the guide!

**Comment by nordlander** [comment]
Well, the situation is actually somewhat simpler! The notion of (a)syncronicity really just applies to actors and their methods; for everything else (standalone functions, class methods, class instantiations, etc) I like to think that the notion of a "plain old subroutine call" is a better intuition. These subroutine calls are intended to behave exactly as they do in Python, as there are no actors involved (besides the current one, possibly, but even that knowledge is irrelevant to a subroutine call). 

Modules are thus neither synchronous nor asynchronous, they just define a set of identifiers in a purely declarative manner. These identifiers might denote functions, classes, actors or initialized values of some type. It's even ok to rely on function calls or class instantiations during a module's initialization as long as these don't attempt to create or call any actors (this is checked by the effect inference of Acton's type-checker).

Actor instantiations are furthermore always synchronous. So it's really just for actor method calls that the synchronos/asynchronous distinction is valid. And here the rule is: every method call is synchronous unless either (1) the call is a statement that discards its result and the callee is not the current actor, or (2) the call is wrapped inside the 'async' keyword.

**Comment by nordlander** [comment]
Unlike Python we don't allow the 'async' keyword on method definitions, since the notion doesn't apply to anything but actor methods and these are furthermore not tied to a particular form of invocation -- it's the caller that decides!

**Comment by nordlander** [comment]
On the topic of wrapping C libraries: I don't think the question of asynchronous vs. synchronous invocation needs to come up at all since no existing C libraries can by definition implement any actor methods. So when wrapping C code, every call is a plain old subroutine call.

Whether a good interface ought to wrap some C functions inside an actor definition is a separate issue, though. I think this might be a preferable solution for some cases where the C code somehow  implicitly manages mutable state. But now we're talking the heavy stuff, so let's defer that discussion until the need comes up.

**Comment by plajjan** [comment]
@nordlander right, yeah, I was thinking that the C-lib-wrapping developer would like to take a decision on whether it makes sense to wrap things up in a synchronous interface or allow for async call, i.e. dress it up as a class or an actor.

**Comment by nordlander** [comment]
@plajjan Yes, eventually that will be required. But then it won't just be about wrapping up a particular call, but rather turning a set of functions into something that truly looks like an actor that maintains a shared state. And I dfinitely think this will need some tools support in order to be manageable.

The option of wrapping up C functions so that they look like a regular class is probably going to be simpler, but still require inside knowledge on how actonc represents classes. Many details to document!

**Comment by plajjan** [comment]
@nordlander yes yes, the guide will naturally need to cover how to dress things up as classes and actors. I might have a somewhat naive view here, but I don't see how it is that much "inside knowledge" - ISTM it is just reiterating on the same work pattern, .e.g:
- write something in a .act file, like a class with methods returning or saving things in object attributes
- `--cgen` and look at output
- replace content of certain actor method functions etc (heh, "method functions" - what a contradiction - but they are functions in C!)
- compile and profit!

**Comment by plajjan** [comment]
I guess I will have to implement a class and actor and I will find out just how hard it is. I'm a complete C noob, so in a way, everything is "inside knowledge" :stuck_out_tongue_closed_eyes:

**Comment by nordlander** [comment]
From a C point of view, a "class" consists of:

1. A struct type that shows the method signatures of the class
2. A global variable of the above type that contains function pointers to the actual methods (the method table)
3. A struct type that shows the data layout of of the class instances, including a method table pointer in slot 0
4. A function that creates instances of the class (allocates memory, sets the method table pointer and calls __init__)
5. Wrappers/implementations of the method functions, all taking an instance pointer as the first argument

On top of that there are some mandatory methods that need to be present in the method table, and all identifiers introduced above need to comply with a certain naming schema. Inheriting a base class or extending a protocol involves even more things to consider.

Most details are actually possible to extract by compiling a dummy class with dummy methods, though. And I'm thinking: wouldn't it be slightly better if we could provide arbitrarily much code when compiling with the --stub flag, and have the compiler mark the parts that are missing as comments in the generated C code (perhaps directed by some clever use of the ellipsis (...) or NotImplemented built-in constants)?
